POSTGRES:
  POSTGRES_HOST: localhost
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_PORT: 6543
  POSTGRES_DATABASE: postgres
  POSTGRES_SSL_MODE: disable
  POSTGRES_TIME_ZONE: Asia/Shanghai

MYSQL:
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PORT: 3306
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: mysql
  MYSQL_CHARSET: utf8mb4
  MYSQL_PARSE_TIME: True
  MYSQL_LOC: Local
