basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:4001
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取用户
      tags:
      - User
  /api/v1/user/create:
    put:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: id
        in: path
        name: ID
        required: true
        type: integer
      - description: name
        in: path
        name: Name
        required: true
        type: string
      - description: account
        in: path
        name: Account
        required: true
        type: string
      - description: role
        in: path
        name: Role
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 创建用户
      tags:
      - User
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
